package au.com.thoughtpatterns.djs.lib

import java.io.File
import java.io.PrintWriter
import scala.Option.option2Iterable
import au.com.thoughtpatterns.core.util.CsvUtils
import au.com.thoughtpatterns.djs.disco.Disco
import au.com.thoughtpatterns.djs.disco.Types._
import au.com.thoughtpatterns.djs.util.RecordingDate
import au.com.thoughtpatterns.djs.disco.Types.SpanishWord
import au.com.thoughtpatterns.djs.disco.Disco
import au.com.thoughtpatterns.djs.clementine.Player
import java.util.Date
import au.com.thoughtpatterns.djs.clementine.Clementine
import au.com.thoughtpatterns.djs.clementine.Analyzer
import au.com.thoughtpatterns.djs.disco.tangotunes.TangoTunes
import au.com.thoughtpatterns.djs.model.PerformanceIdentifier

object Library_Test {

  def str(x: Object) : String = if (x == null) { "" } else { x.toString() }

  def main(args: Array[String]) {

    val l = Library.load(new File("/media/djs/Orange/orange-library2.djs"));

    val tfb = Array(
        "Nueve de julio",
    "Nueve puntos",
    "A bailar",
    "A Evaristo Carriego",
    "A fuego lento",
    "A la gran muñeca",
    "A la parrilla",
    "A los amigos",
    "A media luz",
    // "A mis manos",
    "El abrojito",
    // "Absurdo",
    // "Acompañada y sola",
    "Acuérdate de mí",
    "El adiós",
    // "Adiós juventud",
    // "Adiós muchachos",
    // "Adiós nonino",
    // "Afiches",
    // "Aguila real",
    "Al galope",
    // "Alguien le dice al tango",
    "Alma en pena",
    "El amanecer",
    "Amigazo",
    "Amurado",
    "Anclao en París",
    // "Anda que te cure lola",
    "El andariego",
    "Anoche",
    "El apache argentino",
    // "Araca",
    "Arrabal",
    "Arrabalera",
    // "Azabache",
    "Bahía Blanca",
    "Bailemos",
    // "Bailonga",
    "Bajo un cielo de estrellas",
    "Balada para un loco",
    "Baldosa floja",
    "El baquiano | El baqueano",
    // "Bar",
    "Barrio de tango",
    "Berretín",
    "Bien criolla y bien porteña",
    "Bien milonga",
    "Boedo",
    "La bordona",
    "Bordoneo y 900",
    "La bruja",
    "Buen amigo",
    // "Buen compleaños",
    // "Buenos aires-tokio",
    "C.T.V.",
    // "La cabrera",
    "El caburé",
    "El cachafaz",
    "La cachila",
    "Cachirulo",
    "Cafetín de Buenos Aires",
    "Cambalache",
    "Caminito",
    "Campo afuera",
    "Canaro",
    "Canaro en Paris",
    "La cara de la luna",
    "Cara sucia",
    // "Carmen",
    "Cascabelito",
    "Caseron de tejas",
    "La casita de mis viejos | La casita de mis padres",
    // "Celos",
    "Champagne tango",
    "El chamuyo",
    "Che, bandoneón",
    // "Ché Buenos Aires",
    "El chino Pantaleón",
    "Chiqué",
    // "Chiquilín de bachín",
    "El choclo",
    "Cicatrices",
    "La cicatriz",
    "El ciruja",
    "La clavada",
    "Comme il faut",
    "Como dos extraños",
    // "Con los amigos",
    // "Contrabajeando",
    "Copacabana",
    "Corazón de oro",
    "Corralera",
    "Corrientes y Esmeralda",
    // "La criolla",
    "Las cuarenta",
    "Cuartito azul",
    "Cuesta abajo",
    "La cumparsita",
    "Dandy",
    "Danzarín",
    "De mi arrabal",
    "De mi barrio",
    "De pura cepa",
    "De puro guapo",
    // "Decarísimo",
    "Derecho viejo",
    "Desde el alma",
    // "Desencuentro",
    "El día que me quieras",
    "Didí",
    // "Disonante",
    "Divina",
    "Dominguera",
    "Don Agustín Bardi",
    "Don Esteban",
    "Don Juan",
    "Dos fracasos",
    "Duelo criollo",
    "Los ejes de mi carreta",
    "Ella es así",
    "Emancipación",
    "En esta tarde gris",
    // "Enamorado estoy",
    "El encopao",
    "Ensueños",
    "Entrador",
    "El entrerriano",
    "Es en vano llorar",
    // "Escalas en azul",
    "El esquinazo",
    "Esta noche",
    "Este es el rey",
    "Farolito de mi barrio",
    "Felicia",
    "El firulete",
    "El flete",
    // "Flirteando",
    "Flor de fango",
    "Flor de lino",
    "Flores del alma",
    "Flores negras",
    "Francia",
    "Fuegos artificiales",
    "Fueron tres años",
    "Fueye",
    "Fuimos",
    "Gallo ciego",
    "Garúa",
    "Garufa",
    "Gota de lluvia",
    "Gricel",
    // "Grillito",
    "Griseta",
    "Guapo y varón",
    "La guitarrita",
    "Hotel Victoria",
    "La huella",
    "El huracán",
    "Ilusión de mi vida",
    "Ilusión marina",
    "Indiferencia",
    "El ingeniero",
    "Inspiracion",
    "El internado",
    "El irresistible",
    // "Isabelita",
    // "Jacinto chiclana",
    "El jagüel",
    "Jueves",
    "Julián",
    "La vi llegar",
    "Lágrimas",
    "Lágrimas y sonrisas",
    // "Lejana tierra mía",
    // "Libertango",
    "El llorón",
    // "La llorona",
    // "Lluvia de estrellas",
    "Lo pasao pasó",
    "Lo que vendrá",
    "Lo ví en tus ojos",
    "Loca",
    "Loca bohemia",
    "La loca de amor",
    // "Loca ilusión",
    // "Locura",
    "Lorenzo",
    "Luna de arrabal",
    // "Luz mala",
    "Madame Ivonne",
    "Madre",
    "Madre mía",
    "La madrugada",
    "Mal de amores",
    "Mala junta",
    "Mala pinta",
    "Malandraca",
    "Malena",
    "La maleva",
    "Mama",
    "Mano a mano",
    "Mano brava",
    "Los mareados",
    "Marejada",
    "Margarita Gauthier",
    "Maria",
    "Marinera",
    "Marión",
    "La mariposa",
    "Mariposita",
    "El Marne",
    "Marrón y azul",
    // "Meditación",
    // "Melancolico",
    "Mentías",
    "Mentira",
    "Mi Buenos Aires querido",
    "Mi dolor",
    "Mi noche triste",
    "Mi refugio",
    // "Mi regalo",
    // "Milonga caprichosa",
    "Milonga de mis amores",
    "Milonga del novecientos",
    // "Milonga del angel",
    "Milonga que peina canas",
    "Milonga sentimental",
    "Milonga triste",
    "Milonga, vieja milonga",
    "Milongueando en el cuarenta",
    "Milonguero viejo | Bailarín porteño",
    "Milonguita",
    "Montevideo",
    "Morena",
    "La morocha",
    "Mozo guapo",
    // "Los muchachos",
    "Nada",
    "Nada más",
    "Naranjo en flor",
    "Negra María",
    "Negracha",
    // "Negro el 20",
    "Nido gaucho",
    "Niebla del Riachuelo",
    "No hay tierra como la mía",
    "No me pregunten por qué",
    "No te olvides de mi, corazón",
    "Nobleza de arrabal",
    "Noche de reyes",
    "Nochero soy",
    "Nocturna",
    "Nostalgias",
    // "Nostálgico",
    "Nunca tuvo novio | La que nunca tuvo novio",
    // "Oblivion",
    "Ojos negros",
    "El Once (A divertirse)",
    "Organito de la tarde",
    "Orgullo criollo",
    "Orlando Goñi",
    // "Oro y plata",
    "Pa' que seguir",
    "Pablo",
    "Paciencia",
    "Paisaje",
    // "Pajarito",
    // "Los pajaros perdidos",
    "El paladín",
    "Palomita blanca",
    "Papas calientes",
    "Para dos",
    // "Para lucirse",
    // "Pasión milonguera",
    "Pasional",
    "Patetico",
    "Patotero sentimental",
    "Pavadita",
    // "Payadora",
    "La payanca",
    "Pedacito de cielo",
    // "La pena del payador",
    "Pena mulata",
    "El pensamiento",
    "Pequeña",
    "El pescante",
    // "Piazzolla",
    "Pico blanco",
    "Pobre flor | Primera ilusión",
    "Pobre yo",
    "Poema",
    "Pof pof",
    "El pollo Ricardo",
    "Pompas de jabón",
    "¿Porque?",
    "Por una cabeza",
    "El porteñito",
    "La pulpera de Santa Lucia",
    "La puñalada",
    "Qué falta que me hacés!",
    // "Que fenomeno",
    "Que nadie sepa mi sufrir",
    "Qué noche",
    "Quejas de bandoneon",
    "Quejas del alma",
    // "Racconto",
    "Racing Club",
    "Ramona",
    "Rawson",
    "Re Fa Si",
    "Recién",
    "Recordando",
    "Recuerdo",
    "Recuerdo",
    "Recuerdos de la pampa",
    "Recuerdos de París",
    "Reliquias porteñas",
    // "Responso",
    "Retintín",
    "Retirao",
    // "Rezagao",
    "Rodríguez Peña",
    "Romance de barrio",
    "Romántica",
    "Rondando tu esquina",
    "Rosas de abril",
    "Se dice de mi",
    "Se fue",
    // "Sensiblero",
    "Shusheta",
    "Si sos brujo",
    "Si soy así",
    "Si tú quisieras",
    "Silbando",
    "Silueta porteña",
    // "Sin esperanza",
    "Sin palabras",
    // "Sinvergüenza",
    "Sobre el pucho",
    "Soledad",
    "Soñar y nada más",
    "Sueño de juventud",
    // "Sueño tus besos",
    "Sur",
    "Tabaco",
    "La tablada",
    "Taconeando",
    "Tango brujo",
    "Tango negro",
    // "Tanguango",
    "Tanguera",
    "Taquito militar",
    // "Te llaman malevo",
    // "Te vas milonga",
    // "Tema otoñal",
    "Tierra querida",
    "Tierrita",
    "Tinta verde",
    "Tiny",
    "Toda mi vida",
    "Todo corazón",
    "Tomo y obligo",
    "La torcacita",
    "El torito",
    "Tormenta",
    "Torrente",
    "La trampera",
    // "Trasnoche",
    // "Tremolina",
    "Trenzas",
    "Tristeza criolla",
    "Tristeza marina",
    "Tu angustia y mi dolor",
    "Tu diagnóstico",
    "Tú, el cielo y tú",
    "Tu olvido",
    "La última cita",
    // "La última curda",
    // "El último café",
    "Un momento",
    "Un placer",
    "Una noche de garufa",
    "Unión Cívica",
    // "Universo",
    "Uno",
    // "El vals y tú",
    "Valsecito amigo",
    "Ventarrón",
    "Verdemar",
    "Vida mía",
    "Vieja amiga",
    "Violetas",
    "La viruta",
    "Volver",
    // "Vuelvo al sur",
    // "Yerba loca",
    // "La yerra",
    "Yira, yira",
    "Yo no sé que me han hecho tus ojos",
    "Yo te bendigo",
    "La yumba",
    "Yunta brava",
    "Yunta de oro",
    "Yuyo verde",
    "Zorro gris"
    );
    
    
    var x = l.m.tvm.title("XXX");
    for (t <- tfb) {
      x = (x || l.m.tvm.title(t)).m
    }

    print(x.size)
    
    x.replRetune("/media/djs/Orange/Music", "/tmp/test");
    
    
  }
}