#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )


export JAVA_HOME=/usr/local/jdk1.8.0_101
export SCALA_HOME=/usr/local/scala-2.11.8
export PATH=/usr/local/scala-2.11.8/bin:/usr/local/jdk1.8.0_101/bin:/usr/bin

lib=$SCALA_HOME/lib



bootcp=$lib/scala-compiler.jar:$lib/scala-library.jar:$lib/scala-reflect.jar:$lib/jline.jar:$lib/jline-2.12.jar

cp=$DIR/build/lib/dj.jar:$DIR/library/beatroot-0.5.8.jar:$DIR/library/beatroot-dj.jar:$DIR/library/jline-1.0.jar:$DIR/library/jrtf-0.7.jar:$DIR/library/jrtf-0.7-javadoc.jar:$DIR/library/jrtf-0.7-sources.jar:$DIR/library/json_simple-1.1.jar:$DIR/library/jsoup-1.13.1.jar:$DIR/library/jsoup-1.13.1-sources.jar:$DIR/library/junit-4.3.1.jar:$DIR/library/junit-4.3.1-src.jar:$DIR/library/log4j-1.2.14.jar:$DIR/library/taglib.jar:$DIR/../core/build/lib/thoughtpatterns_core.jar

java -Xbootclasspath/p:$bootcp -cp $cp au.com.thoughtpatterns.djs.app.App $@

