package au.com.thoughtpatterns.djs.disco

object Fakebook {
  
    val tfb = Array(
        "Nueve de julio",
    "Nueve puntos",
    "A bailar",
    "A Evaristo Carriego",
    "A fuego lento",
    "A la gran muñeca",
    "A la parrilla",
    "A los amigos",
    "A media luz",
    // "A mis manos",
    "El abrojito",
    // "Absurdo",
    // "Acompañada y sola",
    "Acuérdate de mí",
    "El adiós",
    // "Adiós juventud",
    // "Adiós muchachos",
    // "Adiós nonino",
    // "Afiches",
    // "Aguila real",
    "Al galope",
    // "Alguien le dice al tango",
    "Alma en pena",
    "El amanecer",
    "Amigazo",
    "Amurado",
    "Anclao en París",
    // "Anda que te cure lola",
    "El andariego",
    "Anoche",
    "El apache argentino",
    // "Araca",
    "Arrabal",
    "Arrabalera",
    // "Azabache",
    "Bahía Blanca",
    "Bailemos",
    // "Bailonga",
    "Bajo un cielo de estrellas",
    "Balada para un loco",
    "Baldosa floja",
    "El baquiano | El baqueano",
    // "Bar",
    "Barrio de tango",
    "Berretín",
    "Bien criolla y bien porteña",
    "Bien milonga",
    "Boedo",
    "La bordona",
    "Bordoneo y 900",
    "La bruja",
    "Buen amigo",
    // "Buen compleaños",
    // "Buenos aires-tokio",
    "C.T.V.",
    // "La cabrera",
    "El caburé",
    "El cachafaz",
    "La cachila",
    "Cachirulo",
    "Cafetín de Buenos Aires",
    "Cambalache",
    "Caminito",
    "Campo afuera",
    "Canaro",
    "Canaro en París",
    "La cara de la luna",
    "Cara sucia",
    // "Carmen",
    "Cascabelito",
    "Caseron de tejas",
    "La casita de mis viejos | La casita de mis padres",
    // "Celos",
    "Champagne tango",
    "El chamuyo",
    "Che, bandoneón",
    // "Ché Buenos Aires",
    "El chino Pantaleón",
    "Chiqué",
    // "Chiquilín de bachín",
    "El choclo",
    "Cicatrices",
    "La cicatriz",
    "El ciruja",
    "La clavada",
    "Comme il faut",
    "Como dos extraños",
    // "Con los amigos",
    // "Contrabajeando",
    "Copacabana",
    "Corazón de oro",
    "Corralera",
    "Corrientes y Esmeralda",
    // "La criolla",
    "Las cuarenta",
    "Cuartito azul",
    "Cuesta abajo",
    "La cumparsita",
    "Dandy",
    "Danzarín",
    "De mi arrabal",
    "De mi barrio",
    "De pura cepa",
    "De puro guapo",
    // "Decarísimo",
    "Derecho viejo",
    "Desde el alma",
    // "Desencuentro",
    "El día que me quieras",
    "Didí",
    // "Disonante",
    "Divina",
    "Dominguera",
    "Don Agustín Bardi",
    "Don Esteban",
    "Don Juan",
    "Dos fracasos",
    "Duelo criollo",
    "Los ejes de mi carreta",
    "Ella es así",
    "Emancipación",
    "En esta tarde gris",
    // "Enamorado estoy",
    "El encopao",
    "Ensueños",
    "Entrador",
    "El entrerriano",
    "Es en vano llorar",
    // "Escalas en azul",
    "El esquinazo",
    "Esta noche",
    "Este es el rey",
    "Farolito de mi barrio",
    "Felicia",
    "El firulete",
    "El flete",
    // "Flirteando",
    "Flor de fango",
    "Flor de lino",
    "Flores del alma",
    "Flores negras",
    "Francia",
    "Fuegos artificiales",
    "Fueron tres años",
    "Fueye",
    "Fuimos",
    "Gallo ciego",
    "Garúa",
    "Garufa",
    "Gota de lluvia",
    "Gricel",
    // "Grillito",
    "Griseta",
    "Guapo y varón",
    "La guitarrita",
    "Hotel Victoria",
    "La huella",
    "El huracán",
    "Ilusión de mi vida",
    "Ilusión marina",
    "Indiferencia",
    "El ingeniero",
    "Inspiración",
    "El internado",
    "El irresistible",
    // "Isabelita",
    // "Jacinto chiclana",
    "El jagüel",
    "Jueves",
    "Julián",
    "La vi llegar",
    "Lágrimas",
    "Lágrimas y sonrisas",
    // "Lejana tierra mía",
    // "Libertango",
    "El llorón",
    // "La llorona",
    // "Lluvia de estrellas",
    "Lo pasao pasó",
    "Lo que vendrá",
    "Lo ví en tus ojos",
    "Loca",
    "Loca bohemia",
    "La loca de amor",
    // "Loca ilusión",
    // "Locura",
    "Lorenzo",
    "Luna de arrabal",
    // "Luz mala",
    "Madame Ivonne",
    "Madre",
    "Madre mía",
    "La madrugada",
    "Mal de amores",
    "Mala junta",
    "Mala pinta",
    "Malandraca",
    "Malena",
    "La maleva",
    "Mama",
    "Mano a mano",
    "Mano brava",
    "Los mareados",
    "Marejada",
    "Margarita Gauthier",
    "Maria",
    "Marinera",
    "Marión",
    "La mariposa",
    "Mariposita",
    "El Marne",
    "Marrón y azul",
    // "Meditación",
    "Melancólico",
    "Mentías",
    "Mentira",
    "Mi Buenos Aires querido",
    "Mi dolor",
    "Mi noche triste",
    "Mi refugio",
    // "Mi regalo",
    // "Milonga caprichosa",
    "Milonga de mis amores",
    "Milonga del novecientos",
    // "Milonga del angel",
    "Milonga que peina canas",
    "Milonga sentimental",
    "Milonga triste",
    "Milonga, vieja milonga",
    "Milongueando en el cuarenta",
    "Milonguero viejo | Bailarín porteño",
    "Milonguita",
    "Montevideo",
    "Morena",
    "La morocha",
    "Mozo guapo",
    // "Los muchachos",
    "Nada",
    "Nada más",
    "Naranjo en flor",
    "Negra María",
    "Negracha",
    // "Negro el 20",
    "Nido gaucho",
    "Niebla del Riachuelo",
    "No hay tierra como la mía",
    "No me pregunten por qué",
    "No te olvides de mi, corazón",
    "Nobleza de arrabal",
    "Noche de reyes",
    "Nochero soy",
    "Nocturna",
    "Nostalgias",
    // "Nostálgico",
    "Nunca tuvo novio | La que nunca tuvo novio",
    // "Oblivion",
    "Ojos negros",
    "El Once",
    "Organito de la tarde",
    "Orgullo criollo",
    "Orlando Goñi",
    // "Oro y plata",
    "Pa' que seguir",
    "Pablo",
    "Paciencia",
    "Paisaje",
    // "Pajarito",
    // "Los pajaros perdidos",
    "El paladín",
    "Palomita blanca",
    "Papas calientes",
    "Para dos",
    // "Para lucirse",
    // "Pasión milonguera",
    "Pasional",
    "Patetico",
    "Patotero sentimental",
    "Pavadita",
    // "Payadora",
    "La payanca",
    "Pedacito de cielo",
    // "La pena del payador",
    "Pena mulata",
    "El pensamiento",
    "Pequeña",
    "El pescante",
    // "Piazzolla",
    "Pico blanco",
    "Pobre flor | Primera ilusión",
    "Pobre yo",
    "Poema",
    "Pof pof",
    "El pollo Ricardo",
    "Pompas de jabón",
    "¿Porque?",
    "Por una cabeza",
    "El porteñito",
    "La pulpera de Santa Lucia",
    "La puñalada",
    "Qué falta que me hacés!",
    // "Que fenomeno",
    "Que nadie sepa mi sufrir",
    "Qué noche",
    "Quejas de bandoneón",
    "Quejas del alma",
    // "Racconto",
    "Racing Club",
    "Ramona",
    "Rawson",
    "Re Fa Si",
    "Recién",
    "Recordando",
    "Recuerdo",
    "Recuerdo",
    "Recuerdos de la pampa",
    "Recuerdos de París",
    "Reliquias porteñas",
    // "Responso",
    "Retintín",
    "Retirao",
    // "Rezagao",
    "Rodríguez Peña",
    "Romance de barrio",
    "Romántica",
    "Rondando tu esquina",
    "Rosas de abril",
    "Se dice de mi",
    "Se fue",
    // "Sensiblero",
    "Shusheta",
    "Si sos brujo",
    "Si soy así",
    "Si tú quisieras",
    "Silbando",
    "Silueta porteña",
    // "Sin esperanza",
    "Sin palabras",
    // "Sinvergüenza",
    "Sobre el pucho",
    "Soledad",
    "Soñar y nada más",
    "Sueño de juventud",
    // "Sueño tus besos",
    "Sur",
    "Tabaco",
    "La tablada",
    "Taconeando",
    "Tango brujo",
    "Tango negro",
    // "Tanguango",
    "Tanguera",
    "Taquito militar",
    // "Te llaman malevo",
    // "Te vas milonga",
    // "Tema otoñal",
    "Tierra querida",
    "Tierrita",
    "Tinta verde",
    "Tiny",
    "Toda mi vida",
    "Todo corazón",
    "Tomo y obligo",
    "La torcacita",
    "El torito",
    "Tormenta",
    "Torrente",
    "La trampera",
    // "Trasnoche",
    // "Tremolina",
    "Trenzas",
    "Tristeza criolla",
    "Tristeza marina",
    "Tu angustia y mi dolor",
    "Tu diagnóstico",
    "Tú, el cielo y tú",
    "Tu olvido",
    "La última cita",
    // "La última curda",
    // "El último café",
    "Un momento",
    "Un placer",
    "Una noche de garufa",
    "Unión Cívica",
    // "Universo",
    "Uno",
    // "El vals y tú",
    "Valsecito amigo",
    "Ventarrón",
    "Verdemar",
    "Vida mía",
    "Vieja amiga",
    "Violetas",
    "La viruta",
    "Volver",
    // "Vuelvo al sur",
    // "Yerba loca",
    // "La yerra",
    "Yira, yira",
    "Yo no sé que me han hecho tus ojos",
    "Yo te bendigo",
    "La yumba",
    "Yunta brava",
    "Yunta de oro",
    "Yuyo verde",
    "Zorro gris",
    
        //"Absurdo",
    "Adiós, muchachos",
    // "Afiches",
    "Homero",
    "Ahora no me conocés",
    "Al compás del corazón",
    "Alma de bohemio",
    "Alma en pena",
    "Amarras",
    "Amurado",
    "Anclao en París",
    // "Aquaforte",
    // "Arrabal amargo",
    "Así se baila el tango",
    "Atenti pebeta",
    "Ave de paso",
    // "Azabache",
    "Bajo el cono azul",
    "Bajo un cielo de estrellas",
    "Balada para un loco",
    // "Bandoneón arrabalero",
    "Barrio de tango",
    "Barrio pobre",
    "Besos brujos",
    "Buscandote",
    "Cafetín de Buenos Aires",
    // "Callejón",
    "Cambalache",
    "Caminito",
    "Campo afuera",
    "Canción desesperada",
    "Cantor de barrio",
    "Caserón de tejas",
    "Cautivo",
    "Charlemos",
    "Che, bandoneón",
    // "Chiquilín de Bachín",
    "Chorra",
    "Cobardía",
    "Como abrazado a un rencor",
    "Como dos extraños",
    "Corrientes y Esmeralda",
    "Cristal",
    // "Cuando tú no estás",
    "Cuesta abajo",
    "De qué podemos hablar",
    "Desde el alma",
    // "Desencuentro",
    "Después",
    "Destellos",
    "Duelo criollo",
    // "Duerme",
    "El abrojito",
    "El adiós",
    "El bulín de la calle Ayacucho",
    "El choclo",
    // "El corazón al sur",
    "El día que me quieras",
    "El encopao",
    // "El último café",
    // "El último organito",
    "El milagro",
    "El motivo | Pobre paica",
    "El viejo vals",
    "En carne propia",
    "En esta tarde gris",
    "En un beso la vida",
    "Esta noche de luna",
    // "Fangal",
    "Farol",
    "Flor de lino",
    "Flores del alma",
    "Flores negras",
    "Fruta amarga",
    "Fueron tres años",
    "Fueye",
    "Fuimos",
    "Garúa",
    // "Garganta con arena",
    "Garras",
    "Garufa",
    // "Golondrinas",
    "Gota de lluvia",
    "Gricel",
    "Griseta",
    "Hasta siempre, amor",
    "La abandoné y no sabía",
    // "La casita de mis viejos",
    "La última copa",
    // "La última curda",
    "La luz de un fósforo",
    "La mariposa",
    "La mentirosa | Mentirosa",
    "La morocha",
    "La noche que te fuiste",
    "La pulpera de Santa Lucía",
    "La vi llegar",
    "Los cosos de al lao",
    "Los mareados",
    "Mañana zarpa un barco",
    "Madame Ivonne",
    "Madreselva",
    "Mala suerte",
    "Malena",
    "Malevaje",
    "Malvón",
    "Mano a mano",
    // "Maquillaje",
    "María",
    "Margarita Gauthier",
    "Marioneta",
    "Mariposita",
    "Más solo que nunca",
    "Melodia de arrabal",
    "Mi Buenos Aires querido",
    // "Mi ciudad y mi gente",
    "Milonga criolla", // additiona, not part of cancionero
    "Milonga del novecientos",
    "Milonga sentimental",
    "Milonga triste",
    "Milonguero viejo | Bailarín porteño",
    "Milonguita",
    "Mimí Pinsón",
    "Mi noche triste",
    "Mi refugio",
    "Mi vieja viola",
    "Muñeca brava",
    "Nada",
    "Nada más",
    "Naranjo en flor",
    "Nido gaucho",
    "Niebla del riachuelo",
    "No hay tierra como la mía",
    "Nostalgias",
    "Nunca tuvo novio | La que nunca tuvo novio",
    "Paisaje",
    "Palomita blanca",
    "Pampero",
    "Pasional",
    "Patotero sentimental",
    "Pedacito de cielo",
    "Pena mulata",
    "Pequeña",
    "Percal",
    "Pero yo se",
    "Pájaro ciego",
    "Por la vuelta",
    "Por una cabeza",
    "Quedémonos aquí",
    "Qué me van a hablar de amor",
    "Quiero verte una vez más",
    "Rebeldía",
    "Recién",
    "Recuerdo malevo",
    "Remolino",
    "Romance de barrio",
    "Rondando tu esquina",
    "Rosa de otoño",
    // "Rubí",
    "Se dice de mí",
    "Se muere de amor",
    "Siga el corso",
    "Silbando",
    "Sin lágrimas",
    "Sin palabras",
    "Soledad",
    "Soñemos",
    "Sueño de juventud",
    "Suerte loca",
    "Sur",
    "Sus ojos se cerraron",
    // "Tarde",
    "Tú",
    "Tabaco",
    "Tal vez será su voz",
    "Temblando",
    "Tinta roja",
    "Toda mi vida",
    "Tormenta",
    // "Tormento",
    "Trenzas",
    "Tres amigos",
    "Tres esquinas",
    "Tristeza marina",
    "Tristezas de la calle Corrientes",
    "Tu pálida voz",
    "Una canción",
    "Una emoción",
    "Una vez",
    "Uno",
    "Vendrás alguna vez?",
    "Ventanita de arrabal",
    "Ventarrón",
    "Vida mía",
    "Viejas alegrías",
    "Viejo smoking",
    "Volver",
    // "Volvió una noche",
    "Yira, yira",
    "Yo no sé llorar",
    "Yo te bendigo",
    "Y todavía te quiero",
    "Yuyo verde"

    );

  
}