create table test_person (
    id bigint generated by default as identity (start with 100) primary key,
    given_name varchar(20),
    family_name varchar(20),
    audit_id bigint
);

insert into test_person ( id, given_name, family_name, audit_id ) values ( 1, 'Jorge', 'Banderas', 1 );
insert into test_person ( id, given_name, family_name, audit_id ) values ( 2, 'rumplestiltskin', 'witchety-grub', 1 );
insert into test_person ( id, given_name, family_name, audit_id ) values ( 3, 'rupert', 'bear', 1 );
